# Config for executing queries.
REST: '10.0.0.36:2059' 
OPERATOR: # Nodes containing data 
   - '10.0.0.194:2048'
   - '10.0.0.36:2048'
DB: 'lsl_demo' # database to query against 
TABLE: 'ping_sensor' # table to query against 
TABLE COLUMNS: # Columns in table to be  used for testing 
   - device_name: 'string' # CHAR, VARCHAR, UUID, etc.
   - parentelement: 'string' # CHAR, VARCHAR, UUID, etc.
   - value: 'numeric' # INT, FLOAT, DOUBLE, NUMERIC, etc.
   #- timestamp: 'timestamp' 
# For WHERE conditions, the minimum and maxium number of days back 
MIN DAYS BACK: 63 
MAX DAYS BACK: 70
